Listed all the memory relays from the 100 pickups
blakespangenberg/randomprime pull request #55
Opened 2022-07-07 08:51 UTC by UltiNaruto

Added pickup memory relay logging to resource_tracing.rs
Implemented id generation for custom pickups

2022-07-07 16:31 UTC, toasterparty requested changes
Please update comments like this one to reflect what is actually being done:

https://github.com/toasterparty/randomprime/pull/55/files#diff-4e76dd88afada4ac87706bb06b3bdc157c736afcb0e50db60232f31b0378c57aL1343-L1345

2022-07-07 16:31 UTC, toasterparty commented on src/bin/resource_tracing.rs
> +    let memory_relay_id = if memory_relay.is_some() {
Is this ever false? If not, please write this in a way that fails if something unexpected happens.

2022-07-07 16:31 UTC, toasterparty commented on src/patches.rs
> +                                    },
Why not just have `memory_relay: pickup_meta::ScriptObjectLocation` as your input instead of fabricating data?

2022-07-08 00:35 UTC, UltiNaruto commented on src/patches.rs
> +                                    },
separate the id and position in the args would be the way then

2022-07-08 02:15 UTC, toasterparty approved these changes

2022-07-08 02:15 UTC, merged